import { Announcement } from "./announcement.types";

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-001",
    eventId: "evt-001",
    title: "Venue Change: Main Hall moved to Hall B",
    body: "Due to last-minute renovations, the keynote and all main-stage sessions will now be held in Hall B, located on the ground floor. All signage has been updated.",
    category: "venue",
    priority: "critical",
    author: { id: "org-1", name: "Event Organizer", avatarUrl: undefined },
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    isRead: false,
    isPinned: true,
  },
  {
    id: "ann-002",
    eventId: "evt-001",
    title: "Workshop Schedule Updated",
    body: "The React Advanced Patterns workshop has been moved from 2 PM to 4 PM. All registered attendees have been notified via email.",
    category: "schedule",
    priority: "high",
    author: { id: "org-1", name: "Event Organizer" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    isRead: false,
    isPinned: false,
  },
  {
    id: "ann-003",
    eventId: "evt-001",
    title: "New Speaker Added: Sarah Chen",
    body: "We are thrilled to announce that Sarah Chen, CTO of Vercel, will be joining us for a special fireside chat at 5 PM. Seats are limited — add it to your schedule now.",
    category: "speaker",
    priority: "medium",
    author: { id: "org-1", name: "Event Organizer" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    isRead: true,
    isPinned: false,
  },
  {
    id: "ann-004",
    eventId: "evt-001",
    title: "Lunch Break Extended by 30 Minutes",
    body: "Due to the morning sessions running slightly over, the lunch break will be extended to 90 minutes. Use the extra time to explore the expo hall!",
    category: "schedule",
    priority: "low",
    author: { id: "org-1", name: "Event Organizer" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isRead: true,
    isPinned: false,
  },
  {
    id: "ann-005",
    eventId: "evt-001",
    title: "Wi-Fi Credentials",
    body: 'Network: Gatherraa-Event | Password: gather2026! \nFor best performance, use the 5GHz band.',
    category: "general",
    priority: "low",
    author: { id: "org-1", name: "Event Organizer" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    isRead: true,
    isPinned: false,
  },
];